[package]
name = "lunar-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
dirs = "6.0"
flate2 = "1.1"
os_info = "3.12"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha1 = "0.10"
tar = "0.4"
tokio = { version = "1.47", features = ["full"] }
uuid = { version = "1.18", features = ["v4", "serde"] }
zip = "4.6"
